/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathgame;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiSystem;
import javax.sound.midi.MidiUnavailableException;
import javax.sound.midi.Sequencer;
import javax.swing.JLabel;
import javax.swing.Popup;
import javax.swing.PopupFactory;
import javax.swing.Timer;

/**
 *
 * @author Levit Nudi
 */
public class GameUI extends javax.swing.JFrame {

    
//DO NOT RENAME BELOW VARIABLES    
int count_timer = 0;
int max_time = 60;//one minute
int user_score = 0;
int first_number = 0;
int second_number = 0;
int user_guess = 0;
int correct_answer = 0;
int max_number_of_questions = 10;
int number_of_answered_questions = 0;
String beep = "beep.wav";
String music = "music.mid";//feel free to change the music and sound effects
//music will start playing inside formWindowOpened() method. This is called
//when the game window is opened
String score = "score.wav";
//DO NOT RENAME ABOVE VARIABLES 
    /**
     * Creates new form GameUI
     * 
     * 
     * WARNING
     * 
     * ANY FORM OF DISHONESTY OR PLAGIARISM WILL LEAD TO DISQUALIFICATION
     * 
     * 
     * FUNDAMENTALS OF COMPUTER SCIENCE SEM1 (30 points)
     * Instructions
     * 
     * 
     * PART A (10 points)
     * 1. Let Quit menu button close the application
     * 2. disable guess button when time is up (use setEnabled(false) method on the button) and enable it
     * when game start button is clicked
     * 3. Rename ALL variable names of swing components, e.g labels, button, textFields etc
     * 
     * 
     * PART B (10 points)
     * 1. Create Another GUI using JDialog called HelpDialog similar to AboutDialog
     * 2. Give the dialog a title of 'Help' and use specifications for AboutDialog(font size etc)
     * 3. Use labels to describe how the game is played
     * 4. Use serif font for your descriptions
     * 5. Add a close button similar to the one in AboutDialog and make the click action close the dialog
     * 6. When the user clicks Tutorial under help menu, let it open HelpDialog (see how AboutDialog opens)
     * 
     * 
     * PART C (10 points)
     * 1. Package application using launch4j
     * 2. Add splash screen and use YOUR OWN icon and image
     * you can get free icons from (http://www.iconarchive.com/tag/ico-files)
     * and any image from google for your splash screen
     * 
     * 
     * ENGINEERING TOOLKIT (30 points)
     * Push your project to github (15 points)
     * detail your github project (15 points)
     * submit your github link by Friday 17th (August) 2018
     * late submissions will not be accepted
     * 
     * 
     * 
     */
    public GameUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Game = new javax.swing.JLabel();
        points = new javax.swing.JLabel();
        Question = new javax.swing.JLabel();
        Timer = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        Points = new javax.swing.JLabel();
        Answer = new javax.swing.JTextField();
        Enter = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        start = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        HelpDialogue = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();
        Tutorial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MAIN GAME");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Game.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Game.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Game.setText("MATH GAME");

        points.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        points.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        points.setText("0");

        Question.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Question.setText("Question");

        Timer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Timer.setText("Timer :");

        Time.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        Time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Time.setText("00:00");

        Points.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Points.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Points.setText("Score :");

        Answer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Enter.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Enter.setText("Guess");
        Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterActionPerformed(evt);
            }
        });

        Menu.setText("File");

        start.setText("Start Game");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        Menu.add(start);

        exit.setText("Quit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        Menu.add(exit);

        MenuBar.add(Menu);

        HelpDialogue.setText("Help");

        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });
        HelpDialogue.add(about);

        Tutorial.setText("Tutorial");
        Tutorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialActionPerformed(evt);
            }
        });
        HelpDialogue.add(Tutorial);

        MenuBar.add(HelpDialogue);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Timer, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Points, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Time, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(82, 82, 82)
                .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Answer)
                    .addComponent(Enter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(Game, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(Game)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Timer)
                    .addComponent(Points))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(points, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        //check the timer class in the code, set repeat and start
        //if timer was running stop it else start        
        count_timer = 0;
        if(!timer.isRunning()){
        timer.setRepeats(true);
        timer.start();
        }else{
            //then restart
            timer.stop();
            timer.setRepeats(true);
            timer.start();
            Enter.setEnabled(true);
        }
        number_of_answered_questions = 0;//reset number of questions answered to 0 if at all above 0
        generateQuestion();
    }//GEN-LAST:event_startActionPerformed

    private void EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterActionPerformed
        // TODO add your handling code here: 
        playSound(beep);
        if(!hasNoInput()){
        //check if user input matches with correct answer
        user_guess = Integer.parseInt(String.valueOf(Answer.getText()));
        if(user_guess == correct_answer){
            
          //increment and display score
            user_score++;
            points.setText(String.valueOf(user_score));
            playSound(score);
            
            //clear previous input
            Answer.setText(null);
            
            //generate next question
            generateQuestion();
           showPopup("Correct!");
        }else{
            //clear previous input
            Answer.setText(null);
            //move to the next question even when user gets wrong
             generateQuestion();
            showPopup("The correct answer is "+correct_answer);
        }
        }else{
            showPopup("Answer cannot be empty!");
        }
        
    }//GEN-LAST:event_EnterActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
      playSound(beep);  
      AboutDialog aboutDialog = new AboutDialog(this, true);
      aboutDialog.show();
    }//GEN-LAST:event_aboutActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
           
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         playSound(music); 
    }//GEN-LAST:event_formWindowOpened

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void TutorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialActionPerformed
        // TODO add your handling code here:
        HelpDialog tutorial=new HelpDialog(this,true);
        tutorial.show();
    }//GEN-LAST:event_TutorialActionPerformed

    //this method will generate a question with two random numbers
    //and display on the question label
    private void generateQuestion(){
      //randomly pick any number between 0 and 4 
      //based on the number picked, the question will
      //either be addition, subtraction, multiplication or division   
        
        
      
        //limit number of questions answered
      if(number_of_answered_questions < max_number_of_questions){  
        
      Random operation = new Random(); 
      
      //pick any random number between 0 and 20      
      first_number = new Random().nextInt(20);
       //pick any random number between 0 and 10 
      second_number = new Random().nextInt(10);      
          
  
      if(operation.nextInt(4)==0){
           Question.setText(first_number+" + "+second_number);
             correct_answer = first_number+second_number; 
              System.out.println("Addition");
             
      }else if(operation.nextInt(4)==1){
           //if operation is 1 let's subtract
             
             Question.setText(first_number+" - "+second_number);
             correct_answer = first_number-second_number;
                   System.out.println("Subtraction");             
      }else if(operation.nextInt(4)==2){
           //if operation is 2 let's multiply    
            
             Question.setText(first_number+" x "+second_number);         
             correct_answer = first_number*second_number; 
                       System.out.println("Multiplication");             
      }else if(operation.nextInt(4)==3){
           //if operation is 3 let's divide      
             Question.setText(first_number+" / "+second_number); 
             if(second_number!=0)
             correct_answer = first_number/second_number; 
             //if you divide a number by zero it throws arithmetic exception
             else correct_answer = first_number;
                           System.out.println("Division");
        
      }else if(operation.nextInt(4)==4){
               //if operation is 4 let's find the remainder when you divide
             Question.setText("Remainder of "+first_number+" / "+second_number);                    
             correct_answer = first_number%second_number; 
                                 System.out.println("Remainder");
      }
      
      number_of_answered_questions++;
      
      }else {
          //stop timer if it was still running
        if(timer.isRunning()){  
        timer.stop();
        }
        Question.setText("You Scored "+user_score+"!");
        Time.setText("Time Taken "+count_timer);
      }
      
    }
    
    //this method checks whether there's any input 
    public boolean hasNoInput(){        
    return Answer.getText().isEmpty();
    }
    
    
    public void showPopup(String message){
        final Popup p = PopupFactory.getSharedInstance()
                .getPopup(Answer, new JLabel(message), Answer.getX(), Answer.getY());
    p.show();
    // create a timer to hide the popup later
    Timer t = new Timer(5000, (ActionEvent e) -> {
        p.hide();
        });
    t.setRepeats(false);
    t.start();
    }
    
        Timer timer = new Timer(1000, new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
          if(count_timer<max_time){    
          Time.setText("Time : "+max_time);
          max_time--;
          }else{
         Time.setText("Time Up!"); 
        Enter.setEnabled(false);
        }
        }
    });  
        
        
        
         // play beep or score sounds sound
   public void playSound(String soundName) {        
       //locate the sounds under resource folder
        URL url = GameUI.class.getResource(soundName);
       if(!soundName.equals(music)){  
          // play only once if not music
       AudioClip clip = Applet.newAudioClip(url);       
       clip.play();
       
       }else{
            try {
                //repeat forever until game is closed
                // ONLY WORKS WITH MIDI FILES !
                // Obtains the default Sequencer connected to a default device.
                URL url2 = GameUI.class.getResource(soundName);
                Sequencer sequencer = MidiSystem.getSequencer();
                //set loop to play until game is closed
                sequencer.setLoopCount(Sequencer.LOOP_CONTINUOUSLY);
                
                // Opens the device, indicating that it should now acquire any
                // system resources it requires and become operational.
                sequencer.open();
                
                // create a stream from a file
                InputStream is = new BufferedInputStream(new FileInputStream(new File(url2.getPath())));
                
                // Sets the current sequence on which the sequencer operates.   
                
                // The stream must point to MIDI file data.
                sequencer.setSequence(is);
                
                // Starts playback of the MIDI data in the currently loaded sequence.
                sequencer.start();
            } catch (MidiUnavailableException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidMidiDataException ex) {
                Logger.getLogger(GameUI.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
   }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameUI().setVisible(true);
        //Once the window is activated / application opens
        //let's play some background music
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JButton Enter;
    private javax.swing.JLabel Game;
    private javax.swing.JMenu HelpDialogue;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel Points;
    private javax.swing.JLabel Question;
    private javax.swing.JLabel Time;
    private javax.swing.JLabel Timer;
    private javax.swing.JMenuItem Tutorial;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel points;
    private javax.swing.JMenuItem start;
    // End of variables declaration//GEN-END:variables
}
